/**
 * Spec Document API — the single authoritative context for writing phase.
 *
 * Generated by merging conception + bible + structure phase summaries
 * into one document. Can be manually edited by user.
 *
 * Stored as data/{slug}/spec.md
 */

import { NextRequest } from "next/server";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { complete, type ModelProvider } from "@/lib/llm";

const DATA_DIR = join(process.cwd(), "data");

function specPath(slug: string): string {
  return join(DATA_DIR, slug, "spec.md");
}

function phasePath(slug: string, phase: string): string {
  return join(DATA_DIR, slug, "phases", `${phase}.md`);
}

function readIfExists(path: string): string | null {
  if (existsSync(path)) return readFileSync(path, "utf-8");
  return null;
}

// GET — read spec document
export async function GET(req: NextRequest) {
  const projectSlug = req.nextUrl.searchParams.get("projectSlug");
  if (!projectSlug) {
    return Response.json({ error: "projectSlug required" }, { status: 400 });
  }

  const path = specPath(projectSlug);
  if (!existsSync(path)) {
    return Response.json({ content: null });
  }

  const content = readFileSync(path, "utf-8");
  return Response.json({ content });
}

// PATCH — manual edit
export async function PATCH(req: NextRequest) {
  try {
    const { projectSlug, content } = (await req.json()) as {
      projectSlug: string;
      content: string;
    };

    if (!projectSlug || content === undefined) {
      return Response.json({ error: "projectSlug and content required" }, { status: 400 });
    }

    const dir = join(DATA_DIR, projectSlug);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(specPath(projectSlug), content, "utf-8");

    return Response.json({ ok: true });
  } catch (err) {
    console.error("spec PATCH error:", err);
    return Response.json({ error: "保存失败" }, { status: 500 });
  }
}

// POST — generate spec by merging phase summaries
export async function POST(req: NextRequest) {
  try {
    const { projectSlug, provider = "deepseek" } = (await req.json()) as {
      projectSlug: string;
      provider?: ModelProvider;
    };

    if (!projectSlug) {
      return Response.json({ error: "projectSlug required" }, { status: 400 });
    }

    // Load all three phase summaries
    const conception = readIfExists(phasePath(projectSlug, "conception"));
    const bible = readIfExists(phasePath(projectSlug, "bible"));
    const structure = readIfExists(phasePath(projectSlug, "structure"));

    if (!conception && !bible && !structure) {
      return Response.json(
        { error: "没有找到任何阶段总结。请先完成至少一个规划阶段。" },
        { status: 400 },
      );
    }

    const parts: string[] = [];
    if (conception) parts.push(`## 构思阶段总结\n\n${conception}`);
    if (bible) parts.push(`## 世界与角色阶段总结\n\n${bible}`);
    if (structure) parts.push(`## 结构阶段总结\n\n${structure}`);

    const merged = parts.join("\n\n---\n\n");

    const systemPrompt = `你是一个创意项目的文档整理员。请将三个阶段的讨论总结合并为一份**写作规格书（Spec）**。

这份 Spec 是写作阶段的唯一权威参考。写手、编辑、审稿人都只看这份文档。

要求：
1. 只保留 ✓ 已确定的内容，去掉讨论过程和待定项
2. 结构清晰，按以下大纲组织
3. 不要添加原文没有的内容
4. 保留所有具体的约束（字数、命名规则、叙述视角等）

输出格式：

# 写作规格书

## Logline
（一句话核心故事）

## 主题与核心冲突
（主题陈述 + 核心矛盾）

## 世界设定
（世界观规则、背景设定）

## 角色档案
（每个角色：名字、身份、want/need、声音特征、弧线）

## 叙事结构
（整体结构、章节/节拍表、叙述视角、时态）

## 命名与用语规则
（各叙事线的命名约定、禁用词、术语使用规则）

## 风格约束
（句子纪律、禁忌、参考标杆）

## 风格锚
（留空，等创作者填入自己认可的1-2段示范文字）

## 字数与篇幅
（总字数目标、每章/beat 预算）`;

    const result = await complete(provider, [
      { role: "user", content: `请将以下阶段总结合并为写作规格书：\n\n${merged}` },
    ], { system: systemPrompt, maxTokens: 8192 });

    if (!result?.trim()) {
      return Response.json({ error: "生成 Spec 失败" }, { status: 500 });
    }

    // Save
    const dir = join(DATA_DIR, projectSlug);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(specPath(projectSlug), result, "utf-8");

    return Response.json({ content: result });
  } catch (err) {
    console.error("spec POST error:", err);
    return Response.json(
      { error: err instanceof Error ? err.message : "生成 Spec 失败" },
      { status: 500 },
    );
  }
}
